pipeline {
    agent {
        node {
            label 'NodeExec' //Label of your Jenkins Node. It can be any. You should change it in order to worker on your Jenkins
        }
    }
     environment {
        CI = true
        customWorkspace = '/var/jenkins_home/workspace/Mercedes'
    }

    stages {
        stage("Build App") {
            steps("Build base image") {
                    sh 'docker-compose build mercedes-benz-app'
            }
        }

        stage("Automated Tests") {
            steps("E2E") {
                    sh 'docker-compose up mercedes-benz-tests'
            }
            post {
                always {
                    sh "docker cp \$(docker-compose ps -aq mercedes-benz-tests):/app/test-results ./"
                    archiveArtifacts artifacts: 'test-results/*', allowEmptyArchive: true
                    archiveArtifacts artifacts: 'src/tests/dataSavedFromTests/*', allowEmptyArchive: true
                }
            }
        }
    }   

    post {
        always {
            sh 'docker-compose down'
        }
    }
}